
/* домен для первичных ключей */
CREATE DOMAIN dintkey
  AS INTEGER NOT NULL
  CHECK (VALUE > 0);

/* домен для первичных ключей */
CREATE DOMAIN ddbkey
  AS INTEGER NOT NULL;

/* будем использовать этот домен для всех полей ссылок */
CREATE DOMAIN dforeignkey
  AS INTEGER;

/* */  
CREATE DOMAIN dmasterkey
  AS INTEGER NOT NULL;

CREATE DOMAIN dlb
  AS INTEGER DEFAULT 1 NOT NULL;

CREATE DOMAIN drb
  AS INTEGER DEFAULT 2 NOT NULL;

CREATE DOMAIN dparent
  AS INTEGER;

CREATE DOMAIN dinteger
  AS INTEGER;

CREATE DOMAIN dinteger_notnull
  AS INTEGER NOT NULL;

CREATE DOMAIN ddouble
  AS DOUBLE PRECISION;

/****************************************************/
/**   Строковые                                    **/
/****************************************************/

CREATE DOMAIN dalias
  AS VARCHAR(8) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dISO
  AS VARCHAR(3) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtemplatetype
  AS VARCHAR(3) CHARACTER SET WIN1251 DEFAULT '' NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dnullalias
  AS VARCHAR(16) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtablename
  AS VARCHAR(31)
  CHECK ((VALUE IS NULL) OR (VALUE > ''));

CREATE DOMAIN dfieldname
  AS VARCHAR(31)
  CHECK ((VALUE IS NULL) OR (VALUE > ''));

CREATE DOMAIN dname
  AS VARCHAR(60) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dlongname 
  AS VARCHAR(80) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dbarcode
  AS VARCHAR(24) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dqueue
  AS VARCHAR(2) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext8
  AS VARCHAR(8) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext10
  AS VARCHAR(10) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext20
  AS VARCHAR(20) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext40
  AS VARCHAR(40) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dbankaccount
  AS VARCHAR(40) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dbankcode
  AS VARCHAR(20) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext60
  AS VARCHAR(60) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext80
  AS VARCHAR(80) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext120
  AS VARCHAR(120) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext180
  AS VARCHAR(180) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext254
  AS VARCHAR(254) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext255
  AS VARCHAR(255) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtext1024
  AS VARCHAR(1024) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dclassname
  AS VARCHAR(40) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dusername
  AS VARCHAR(20) CHARACTER SET WIN1251 NOT NULL 
  CHECK (VALUE > '')
  COLLATE PXW_CYRL;

CREATE DOMAIN dusergroupname
  AS VARCHAR(20) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dpassword
  AS VARCHAR(20) CHARACTER SET WIN1251 NOT NULL 
  CHECK (VALUE > '')
  COLLATE PXW_CYRL;

CREATE DOMAIN dsubsystemname
  AS VARCHAR(20) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN ddecdigits
  AS SMALLINT
  CHECK ((VALUE IS NULL) OR (VALUE BETWEEN 0 AND 16));

CREATE DOMAIN dlanguage
  AS VARCHAR(1);

CREATE DOMAIN daccount
  AS VARCHAR(6) CHARACTER SET WIN1251
  COLLATE PXW_CYRL;

CREATE DOMAIN dtext32
  AS VARCHAR(32) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN druid
  AS VARCHAR(21)
  NOT NULL;

CREATE DOMAIN dtax
  AS DECIMAL(7, 4)
  CHECK ((VALUE IS NULL) OR (VALUE BETWEEN 0 AND 99));

CREATE DOMAIN dpercent
  AS DECIMAL(7, 4);

CREATE DOMAIN dpositive
  AS DECIMAL(15, 8)
  CHECK ((VALUE IS NULL) OR (VALUE >= 0));

CREATE DOMAIN dcurrency
  AS DECIMAL(15, 4);

CREATE DOMAIN dquantity
  AS DECIMAL(15, 4);

CREATE DOMAIN dgoldquantity
  AS NUMERIC(15, 8);

CREATE DOMAIN dfactor
  AS DOUBLE PRECISION;  

CREATE DOMAIN dboolean
  AS SMALLINT
  DEFAULT 0
  CHECK ((VALUE IS NULL) OR (VALUE IN (0, 1)));

CREATE DOMAIN dboolean_notnull
  AS SMALLINT
  DEFAULT 0
  NOT NULL
  CHECK (VALUE IN (0, 1));

CREATE DOMAIN ddisabled
  AS SMALLINT DEFAULT 0
  CHECK ((VALUE IS NULL) OR (VALUE IN (0, 1)));

CREATE DOMAIN dreserved
  AS INTEGER;

CREATE DOMAIN dentryid
  AS VARCHAR(32) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dpersonalid
  AS VARCHAR(16) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dfilename
  AS VARCHAR(255) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

/* почтовый индекс */
CREATE DOMAIN dzipcode
  AS VARCHAR(12);

/* почтовый индекс */
CREATE DOMAIN dpobox
  AS VARCHAR(8);

/* горячая клавиша */
CREATE DOMAIN dhotkey
  AS INTEGER;

/* тэлефонны нумар */
CREATE DOMAIN dtel
  AS VARCHAR(40) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

/* number of pager */
CREATE DOMAIN dpager
  AS VARCHAR(40) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

/* адрас электроннай пошты */
CREATE DOMAIN demail
  AS VARCHAR(40);

/* УРЛ */
CREATE DOMAIN durl
  AS VARCHAR(40);

/* выкарыстоўваецца для захоўвання полу */
/* М -- мужчынск_, F -- жаночы          */
CREATE DOMAIN dgender
  AS VARCHAR(1)
  CHECK ((VALUE IS NULL) OR (VALUE = 'M') OR (VALUE = 'F') OR (VALUE = 'N'));

/* часовой пояс относительно Гринвича */
CREATE DOMAIN dgmtoffset
  AS SMALLINT
  CHECK ((VALUE IS NULL) OR (VALUE >= -12) OR (VALUE <= 12));

CREATE DOMAIN dBMP
  AS BLOB SUB_TYPE 0 SEGMENT SIZE 1024;

CREATE DOMAIN dRTF
  AS BLOB SUB_TYPE 0 SEGMENT SIZE 1024;

CREATE DOMAIN dsecurity
  AS INTEGER DEFAULT -1
  NOT NULL;

CREATE DOMAIN dtextalignment
  AS VARCHAR(1)
  DEFAULT 'L'
  CHECK((VALUE IS NULL) OR (VALUE IN ('L', 'R', 'C', 'J')));  

CREATE DOMAIN daccounttype 
  AS VARCHAR(1)
  CHECK((VALUE IS NULL) OR (VALUE IN ('D', 'K')));

CREATE DOMAIN dpricetype
  AS VARCHAR(1)
  CHECK (VALUE IN ('P', 'C'));

CREATE DOMAIN dcontacttype
  AS VARCHAR(1)
  CHECK (VALUE IN ('D', 'K'));

CREATE DOMAIN dreplicationtype
  AS VARCHAR(1)
  CHECK (VALUE IN ('I', 'U', 'D'));

CREATE DOMAIN dreplidset
  AS VARCHAR(255) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dtypetransport
  AS VARCHAR(1)
  CHECK ((VALUE IS NULL) OR (VALUE IN ('C', 'S', 'R', 'O', 'W')));

CREATE DOMAIN ddate
  AS DATE;

CREATE DOMAIN ddate_notnull
  AS DATE NOT NULL;

CREATE DOMAIN dtime
  AS TIME;

CREATE DOMAIN dtime_notnull
  AS TIME NOT NULL;

CREATE DOMAIN dtimestamp
  AS TIMESTAMP;

CREATE DOMAIN dtimestamp_notnull
  AS TIMESTAMP NOT NULL;

CREATE DOMAIN dsmallint
  AS SMALLINT;

CREATE DOMAIN dversionstring
  AS VARCHAR(20) NOT NULL;

CREATE DOMAIN dfilterdata
  AS BLOB SUB_TYPE 0 SEGMENT SIZE 512;

CREATE DOMAIN dblob4096
  AS BLOB SEGMENT SIZE 4096;

CREATE DOMAIN dblobtext80
  AS BLOB SUB_TYPE 1 SEGMENT SIZE 80;

CREATE DOMAIN dblobtext80_1251
  AS BLOB SUB_TYPE 1 SEGMENT SIZE 80 CHARACTER SET win1251;

CREATE DOMAIN dblob80
  AS BLOB SEGMENT SIZE 80;

CREATE DOMAIN dblob
  AS BLOB;

CREATE DOMAIN dscript
  AS BLOB SUB_TYPE 1 SEGMENT SIZE 1024;

CREATE DOMAIN dreporttemplate
  AS BLOB SEGMENT SIZE 1024;

CREATE DOMAIN djournalblob
  AS BLOB SUB_TYPE 1 SEGMENT SIZE 1024;

CREATE DOMAIN dlisttrtypeconddata
  AS BLOB SUB_TYPE 0 SEGMENT SIZE 512;

CREATE DOMAIN dnumerationblob
  AS BLOB SUB_TYPE 0 SEGMENT SIZE 256;

CREATE DOMAIN dmsgtype
  AS VARCHAR(1) NOT NULL;

CREATE DOMAIN daccountingdiscipline
  AS VARCHAR(1)
  CHECK ((VALUE IS NULL) OR (VALUE IN ('F', 'L', 'A')));

CREATE DOMAIN deditiondate AS
  TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0);

CREATE DOMAIN dcreationdate AS
  TIMESTAMP DEFAULT CURRENT_TIMESTAMP(0);

CREATE DOMAIN ddocumentdate AS
  DATE NOT NULL
  CHECK (VALUE BETWEEN '01.01.1990' AND '31.12.2099');

CREATE DOMAIN ddocumentnumber AS
  VARCHAR(20) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dblob1024 AS 
  BLOB SUB_TYPE 0 SEGMENT SIZE 1024;

CREATE DOMAIN dsubtype AS 
  VARCHAR(31) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN dgdcname AS 
  VARCHAR(64) CHARACTER SET WIN1251 COLLATE PXW_CYRL;

CREATE DOMAIN daccountalias
  AS VARCHAR(40) CHARACTER SET WIN1251 NOT NULL COLLATE PXW_CYRL;

CREATE DOMAIN dfixlength 
  AS INTEGER CHECK ((VALUE IS NULL) OR (VALUE > 0 AND VALUE <= 20));

COMMIT;
