
SET TERM ^ ;

CREATE OR ALTER TRIGGER gd_db_connect
  ACTIVE
  ON CONNECT
  POSITION 0
AS
  DECLARE VARIABLE ingroup INTEGER = NULL;
  DECLARE VARIABLE userkey INTEGER = NULL;
  DECLARE VARIABLE contactkey INTEGER = NULL;
BEGIN
  SELECT FIRST 1 id, contactkey, ingroup 
  FROM gd_user 
  WHERE ibname = CURRENT_USER
  INTO :userkey, :contactkey, :ingroup;
  RDB$SET_CONTEXT('USER_SESSION', 'GD_USERKEY', COALESCE(:userkey, 150001));
  RDB$SET_CONTEXT('USER_SESSION', 'GD_CONTACTKEY', COALESCE(:contactkey, 650002));
  RDB$SET_CONTEXT('USER_SESSION', 'GD_INGROUP', COALESCE(:ingroup, 0));
END
^

SET TERM ; ^

COMMIT;
