with M2 do
begin
// place syntax memo options here
{    BlockColor := clSilver;
    BlockFontColor := clNavy;

    CommentAttr.Color := clRed;
    CommentAttr.Style := [];

    KeywordAttr.Color := clLime;
    KeywordAttr.Style := [fsBold];

    StringAttr.Color := clAqua;
    StringAttr.Style := [];

    TextAttr.Color := clYellow;
    TextAttr.Style := [];

    Color := clBlack;
    Repaint;}

end;
