DELETE FROM gd_command;
COMMIT;
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (702000,NULL,'Меню','menu',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (702500,702000,'Просмотр','view',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (702501,702500,'Исследователь','showexplorer',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (710000,NULL,'Исследователь','explorer',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (715000,710000,'Банк','bank',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (715010,715000,'Платежные поручения','bank_payment_order',0,NULL,17,NULL,'TgdcPaymentOrder',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (715020,715000,'Выписки по р/с','dp_bank_statement',0,NULL,17,NULL,'TgdcBankStatement',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (730000,710000,'Справочники','references',0,NULL,0,NULL,NULL,NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (730100,730000,'Клиенты','ref_contact',0,NULL,0,NULL,'TgdcBaseContact',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (730200,730000,'Курсы валют','ref_curr_rate',0,NULL,0,NULL,'TgdcCurr',NULL,1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (730600,730000,'Рабочие фирмы','ref_work_company',0,NULL,0,NULL,'',NULL,1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (730950,730000,'Административно-территориальные единицы','ref_place',0,NULL,0,NULL,'TgdcPlace',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (731050,730000,'Типы счетов организаций','ref_compacctype',0,NULL,0,NULL,'TgdcCompanyAccountType',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (739500,730000,'Вид использования имущества','ref_assetdest',0,NULL,0,NULL,'Tgdc_dpAssetDest',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (739510,730000,'Указы, постановления','ref_decree',0,NULL,0,NULL,'Tgdc_dpDecree',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740000,710000,'Сервис','service',0,NULL,0,NULL,NULL,NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740050,740000,'Администратор','srv_administrator',0,NULL,15,NULL,'TfrmGAdminMainForm',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740055,740050,'Пользователи','adm_user',0,NULL,52,NULL,'TgdcUser',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740060,740050,'Группы пользователей','adm_user_group',0,NULL,52,NULL,'TgdcUserGroup',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740300,740000,'Хранилище','srv_storage',0,NULL,0,NULL,'Tst_frmMain',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740400,740000,'Атрибуты','srv_attribute',0,NULL,0,NULL,'TfrmUserDefined',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740500,740000,'Региональные установки','regionalsettings',0,NULL,0,NULL,'TdlgRegionalSettings',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740600,740000,'Типовые документы','typedocument',0,NULL,0,NULL,'TgdcDocumentType',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740800,740000,'Макросы','runGlobalMacros',0,NULL,0,NULL,'',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (740900,740000,'Константы','constantes',0,NULL,0,NULL,'TgdcConst',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741101,740400,'Домены','gdcField',0,NULL,17,NULL,'TgdcField',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741102,740400,'Таблицы','gdcTable',0,NULL,17,NULL,'TgdcTable',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741103,740400,'Представления','gdcView',0,NULL,17,NULL,'TgdcView',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741104,740400,'Процедуры','gdcStoredProc',0,NULL,17,NULL,'TgdcStoredProc',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741105,740400,'Исключения','gdcExceptions',0,NULL,17,NULL,'TgdcException',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (741106,740400,'Настройки','gdcSetting',0,NULL,17,NULL,'TgdcSetting',NULL,1,0,0,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (770000,710000,'Отчеты','report',0,NULL,0,NULL,'Tgdc_frmReportList',NULL,1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (799000,710000,'Акты','',0,NULL,0,NULL,'',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (799010,799000,'Акт описи и оценки','ref_inventory',0,NULL,0,NULL,'Tgdc_dpInventory',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (799040,799000,'Акт (протокол) изъятия','ref_withdrawal',0,NULL,0,NULL,'Tgdc_dpWithdrawal',NULL,-1,-1,-1,0,NULL);
INSERT INTO GD_COMMAND
  (ID,PARENT,NAME,CMD,CMDTYPE,HOTKEY,IMGINDEX,ORDR,CLASSNAME,SUBTYPE,AVIEW,ACHAG,AFULL,DISABLED,RESERVED)
VALUES
  (799050,730000,'Назначения платежа','ref_paymentspec',0,NULL,0,NULL,'TgdcDestCode',NULL,-1,-1,-1,0,NULL);
