GRANT ALL TABLE TO ROLE ADMINISTRATOR;
GRANT ALL VIEW TO ROLE ADMINISTRATOR;
GRANT ALL PROCEDURE TO ROLE ADMINISTRATOR;
GRANT ALL FUNCTION TO ROLE ADMINISTRATOR;
GRANT ALL PACKAGE TO ROLE ADMINISTRATOR;
GRANT ALL GENERATOR TO ROLE ADMINISTRATOR;
GRANT ALL SEQUENCE TO ROLE ADMINISTRATOR;
GRANT ALL DOMAIN TO ROLE ADMINISTRATOR;
GRANT ALL EXCEPTION TO ROLE ADMINISTRATOR;
GRANT ALL ROLE TO ROLE ADMINISTRATOR;
GRANT ALL CHARACTER SET TO ROLE ADMINISTRATOR;
GRANT ALL COLLATION TO ROLE ADMINISTRATOR;
GRANT ALL FILTER TO ROLE ADMINISTRATOR;

COMMIT;

